pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                    echo "hostname: $(hostname)" >> test.log
                    echo "date: $(date)" >> test.log
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}