pipeline {
    agent any 

    stages{
        stage('my first stage'){
            steps{
                echo 'Hello WorldZ'
                dat
            }
        }
        
        stage('This is my second stage'){
            steps{
                sh '''
                    free -h
                    whoami
                '''
            }
        }

        stage('This is my third stage'){
            steps{
                sh '''
                    date
                    cal
                '''
            }
        }

        stage('python stage'){
            steps{
                sh '''
                    cd 01-firstjenkinsfile/
                    python3 test.py
                '''
            }
        }
    }
}